:gear: eol: regenerate Dockerfiles

diff --git a/eol/5.020.003-slim,threaded-buster/DevelPatchPerl.patch b/eol/5.020.003-slim,threaded-buster/DevelPatchPerl.patch
--- a/eol/5.020.003-slim,threaded-buster/DevelPatchPerl.patch
+++ b/eol/5.020.003-slim,threaded-buster/DevelPatchPerl.patch
@@ -54,6 +54,21 @@ index 438b926..a762f78 100755
  esac
  case "$mips_type" in
  '');;
+diff --git a/cpan/ExtUtils-MakeMaker/lib/ExtUtils/Liblist/Kid.pm b/cpan/ExtUtils-MakeMaker/lib/ExtUtils/Liblist/Kid.pm
+index e39c8b2..134d3ab 100644
+--- a/cpan/ExtUtils-MakeMaker/lib/ExtUtils/Liblist/Kid.pm
++++ b/cpan/ExtUtils-MakeMaker/lib/ExtUtils/Liblist/Kid.pm
+@@ -154,6 +154,10 @@ sub _unix_os2_ext {
+                 && -f ( $fullname = "$thispth/lib$thislib.$Config_dlext" ) )
+             {
+             }
++            elsif ( $^O eq 'darwin' && require DynaLoader && defined &DynaLoader::dl_load_file
++                && DynaLoader::dl_load_file( $fullname = "$thispth/lib$thislib.$so", 0 ) )
++            {
++            }
+             elsif ( -f ( $fullname = "$thispth/$thislib$Config_libext" ) ) {
+             }
+             elsif ( -f ( $fullname = "$thispth/lib$thislib.dll$Config_libext" ) ) {
 diff --git a/cpan/Time-Local/t/Local.t b/cpan/Time-Local/t/Local.t
 index 472e71a..0a852a0 100644
 --- a/cpan/Time-Local/t/Local.t
@@ -102,165 +117,326 @@ index 472e71a..0a852a0 100644
         '60 day difference between two calls to timegm');
  }
  
-diff --git a/hints/linux.sh b/hints/linux.sh
-index 956adfc..c749f0f 100644
---- a/hints/linux.sh
-+++ b/hints/linux.sh
-@@ -85,7 +85,7 @@ uname_minus_m="${uname_minus_m:-"$targetarch"}"
- 
- # Check if we're about to use Intel's ICC compiler
- case "`${cc:-cc} -V 2>&1`" in
--*"Intel(R) C++ Compiler"*|*"Intel(R) C Compiler"*)
-+*"Intel(R) C"*" Compiler"*)
-     # record the version, formats:
-     # icc (ICC) 10.1 20080801
-     # icpc (ICC) 10.1 20080801
-@@ -165,6 +165,9 @@ esac
- # plibpth to bypass this check.
- if [ -x /usr/bin/gcc ] ; then
-     gcc=/usr/bin/gcc
-+# clang also provides -print-search-dirs
-+elif ${cc:-cc} --version 2>/dev/null | grep -q '^clang ' ; then
-+    gcc=${cc:-cc}
- else
-     gcc=gcc
- fi
-@@ -178,6 +181,33 @@ case "$plibpth" in
+diff --git a/ext/DynaLoader/DynaLoader_pm.PL b/ext/DynaLoader/DynaLoader_pm.PL
+index 5fb52a2..f362fe3 100644
+--- a/ext/DynaLoader/DynaLoader_pm.PL
++++ b/ext/DynaLoader/DynaLoader_pm.PL
+@@ -493,12 +493,18 @@ sub dl_findfile {
+             foreach $name (@names) {
+ 		my($file) = "$dir$dirsep$name";
+                 print STDERR " checking in $dir for $name\n" if $dl_debug;
+-		$file = ($do_expand) ? dl_expandspec($file) : (-f $file && $file);
+-		#$file = _check_file($file);
+-		if ($file) {
++		if ($do_expand && ($file = dl_expandspec($file))) {
++                    push @found, $file;
++                    next arg; # no need to look any further
++		}
++		elsif (-f $file) {
+                     push(@found, $file);
+                     next arg; # no need to look any further
+                 }
++		elsif (dl_load_file($file, 0)) {
++                    push @found, $file;
++                    next arg; # no need to look any further
++		}
+             }
+         }
+     }
+diff --git a/hints/darwin.sh b/hints/darwin.sh
+index e1f20af..fdfbdd4 100644
+--- a/hints/darwin.sh
++++ b/hints/darwin.sh
+@@ -24,20 +24,21 @@ case "$osvers" in
      ;;
  esac
  
-+# For the musl libc, perl should #define _GNU_SOURCE.  Otherwise, some
-+# available functions, like memem, won't be used.  See the discussion in
-+# [perl #133760].  musl doesn't offer an easy way to identify it, but,
-+# at least on alpine linux, the ldd --version output contains the
-+# string 'musl.'
-+case `ldd --version 2>&1` in
-+    musl*)  ccflags="$ccflags -D_GNU_SOURCE" ;;
-+        *) ;;
++# finite() deprecated in 10.9, use isfinite() instead.
++case "$osvers" in
++[1-8].*) ;;
++*) d_finite='undef' ;;
 +esac
 +
-+# libquadmath is sometimes installed as gcc internal library,
-+# so contrary to our usual policy of *not* looking at gcc internal
-+# directories we now *do* look at them, in case they contain
-+# the quadmath library.
-+# XXX This may apply to other gcc internal libraries, if such exist.
-+# XXX This could be at Configure level, but then the $gcc is messy.
-+case "$usequadmath" in
-+"$define")
-+  for d in `LANG=C LC_ALL=C $gcc $ccflags $ldflags -print-search-dirs | grep libraries | cut -f2- -d= | tr ':' $trnl | grep 'gcc' | sed -e 's:/$::'`
-+  do
-+    case `ls $d/*libquadmath*$so* 2>/dev/null` in
-+    $d/*libquadmath*$so*) xlibpth="$xlibpth $d" ;;
+ # This was previously used in all but causes three cases
+ # (no -Ddprefix=, -Dprefix=/usr, -Dprefix=/some/thing/else)
+ # but that caused too much grief.
+ # vendorlib="/System/Library/Perl/${version}"; # Apple-supplied modules
+ 
+-# BSD paths
+-case "$prefix" in
+-'')	# Default install; use non-system directories
+-	prefix='/usr/local';
+-	siteprefix='/usr/local';
+-	;;
+-'/usr')	# We are building/replacing the built-in perl
+-	prefix='/';
+-	installprefix='/';
++case "$darwin_distribution" in
++$define) # We are building/replacing the built-in perl
++	prefix='/usr';
++	installprefix='/usr';
+ 	bin='/usr/bin';
+ 	siteprefix='/usr/local';
+ 	# We don't want /usr/bin/HEAD issues.
+@@ -62,8 +63,6 @@ case "$prefix" in
+ 	siteman1dir='/usr/local/share/man/man1';
+ 	siteman3dir='/usr/local/share/man/man3';
+ 	;;
+-  *)	# Anything else; use non-system directories, use Configure defaults
+-	;;
+ esac
+ 
+ ##
+@@ -180,28 +179,188 @@ case "$ld" in
+         ;;
+ esac
+ 
++# From http://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/mk/platform/Darwin.mk
++# and https://trac.macports.org/wiki/XcodeVersionInfo
++# and https://trac.macports.org/wiki/UsingTheRightCompiler
++# and https://gist.github.com/yamaya/2924292
++# and http://opensource.apple.com/source/clang/
++#
++# Note that Xcode gets updates on older systems sometimes, and in
++# general that the OS levels and XCode levels are not synchronized
++# since new releases of XCode usually support both some new and some
++# old OS releases.
++#
++# Note that Apple hijacks the clang preprocessor symbols __clang_major__
++# and __clang_minor__ so they cannot be used (easily) to detect the
++# actual clang release.  For example:
++#
++# "Yosemite 10.10.x 14.x.y 6.3 (clang 3.6 as 6.1/602.0.49)"
++#
++# means that the Xcode 6.3 provided the clang 6.3 but called it 6.1
++# (__clang_major__, __clang_minor__) and in addition the preprocessor
++# symbol __apple_build_version__ was 6020049.
++#
++# Codename        OS      Kernel  Xcode
++#
++# Cheetah         10.0.x  1.3.1
++# Puma            10.1    1.4.1
++#                 10.1.x  5.x.y
++# Jaguar          10.2.x  6.x.y
++# Panther         10.3.x  7.x.y
++# Tiger           10.4.x  8.x.y   2.0   (gcc4 4.0.0)
++#                                 2.2   (gcc4 4.0.1)
++#                                 2.2.1 (gcc 3.3)
++#                                 2.5 ?
++# Leopard         10.5.x  9.x.y   3.0   (gcc 4.0.1 default)
++#                                 3.1   (gcc 4.2.1)
++# Snow Leopard    10.6.x  10.x.y  3.2   (llvm gcc 4.2, clang 2.3 as 1.0)
++#                                 3.2.1 (clang 1.0.1 as 1.0.1/24)
++#                                 3.2.2 (clang 1.0.2 as 1.0.2/32)
++#                                 3.2.3 (clang 1.5 as 1.5/60)
++#                                 4.0.1 (clang 2.9 as 2.0/138)
++# Lion            10.7.x  11.x.y  4.1   (llvm gcc 4.2.1, clang 3.0 as 2.1/163.7.1)
++#                                 4.2   (clang 3.0 as 3.0/211.10.1)
++#                                 4.3.3 (clang 3.1 as 3.1/318.0.61)
++#                                 4.4   (clang 3.1 as 4.0/421.0.57)
++# Mountain Lion   10.8.x  12.x.y  4.5   (clang 3.1 as 4.1/421.11.65, real gcc removed, there is gcc but it's really clang)
++#                                 4.6   (clang 3.2 as 4.2/425.0.24)
++#                                 5.0   (clang 3.3 as 5.0/500.2.75)
++#                                 5.1   (clang 3.4 as 5.1/503.0.38)
++#                                 5.1.1 (clang 3.4 as 5.1/503.0.40)
++# Mavericks       10.9.x  13.x.y  6.0.1 (clang 3.5 as 6.0/600.0.51)
++#                                 6.1   (clang 3.5 as 6.0/600.0.54)
++#                                 6.1.1 (clang 3.5 as 6.0/600.0.56)
++#                                 6.2   (clang 3.5 as 6.0/600.0.57)
++# Yosemite        10.10.x 14.x.y  6.3   (clang 3.6 as 6.1/602.0.49)
++#                                 6.3.1 (clang 3.6 as 6.1/602.0.49)
++#                                 6.3.2 (clang 3.6 as 6.1/602.0.53)
++# El Capitan      10.11.x 15.x.y  7.0   (clang 3.7 as 7.0/700.0.72)
++#                                 7.1   (clang 3.7 as 7.0/700.1.76)
++#                                 7.2   (clang 3.7 as 7.0.2/700.1.81)
++#                                 7.2.1 (clang 3.7 as 7.0.2/700.1.81)
++#                                 7.3   (clang 3.8 as 7.3.0/703.0.29)
++# Sierra          10.12.x 16.x.y  8.0.0 (clang 3.8 as 8.0/800.0.38)
++#
++
++# Processors Supported
++#
++# PowerPC (PPC):       10.0.x - 10.5.8 (final 10.5.x)
++# PowerPC via Rosetta: 10.4.4 - 10.6.8 (final 10.6.x)
++# IA-32:               10.4.4 - 10.6.8 (though still supported on x86-64)
++# x86-64:              10.4.7 - current
++
++# MACOSX_DEPLOYMENT_TARGET selects the minimum OS level we want to support
++#
++# It is needed for OS releases before 10.6.
++#
++# https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/cross_development/Configuring/configuring.html
++#
++# If it is set, we also propagate its value to ccflags and ldflags
++# using the -mmacosx-version-min flag.  If it is not set, we use
++# the OS X release as the min value for the flag.
++
++# Adds "-mmacosx-version-min=$2" to "$1" unless it already is there.
++add_macosx_version_min () {
++  local v
++  eval "v=\$$1"
++  case " $v " in
++  *"-mmacosx-version-min"*)
++     echo "NOT adding -mmacosx-version-min=$2 to $1 ($v)" >&4
++     ;;
++  *) echo "Adding -mmacosx-version-min=$2 to $1" >&4
++     eval "$1='$v -mmacosx-version-min=$2'"
++     ;;
++  esac
++}
++
+ # Perl bundles do not expect two-level namespace, added in Darwin 1.4.
+ # But starting from perl 5.8.1/Darwin 7 the default is the two-level.
+-case "$osvers" in
+-1.[0-3].*)
++case "$osvers" in  # Note: osvers is the kernel version, not the 10.x
++1.[0-3].*) # OS X 10.0.x
+    lddlflags="${ldflags} -bundle -undefined suppress"
+    ;;
+-1.*)
++1.*)       # OS X 10.1
+    ldflags="${ldflags} -flat_namespace"
+    lddlflags="${ldflags} -bundle -undefined suppress"
+    ;;
+-[2-6].*)
++[2-6].*)   # OS X 10.1.x - 10.2.x (though [2-4] never existed publicly)
+    ldflags="${ldflags} -flat_namespace"
+    lddlflags="${ldflags} -bundle -undefined suppress"
+    ;;
+-*) 
++[7-9].*)   # OS X 10.3.x - 10.5.x
+    lddlflags="${ldflags} -bundle -undefined dynamic_lookup"
+    case "$ld" in
+-       *MACOSX_DEVELOPMENT_TARGET*) ;;
++       *MACOSX_DEPLOYMENT_TARGET*) ;;
+        *) ld="env MACOSX_DEPLOYMENT_TARGET=10.3 ${ld}" ;;
+    esac
+    ;;
++*)        # OS X 10.6.x - current
++   # The MACOSX_DEPLOYMENT_TARGET is not needed,
++   # but the -mmacosx-version-min option is always used.
++
++   # We now use MACOSX_DEPLOYMENT_TARGET, if set, as an override by
++   # capturing its value and adding it to the flags.
++    case "$MACOSX_DEPLOYMENT_TARGET" in
++    [1-9][0-9].*)
++      add_macosx_version_min ccflags $MACOSX_DEPLOYMENT_TARGET
++      add_macosx_version_min ldflags $MACOSX_DEPLOYMENT_TARGET
++      ;;
++    '')
++      # Empty MACOSX_DEPLOYMENT_TARGET is okay.
++      ;;
++    *)
++      cat <<EOM >&4
++
++*** Unexpected MACOSX_DEPLOYMENT_TARGET=$MACOSX_DEPLOYMENT_TARGET
++***
++*** Please either set it to a valid macOS version number (e.g., 10.15) or to empty.
++
++EOM
++      exit 1
++      ;;
 +    esac
-+  done
-+  ;;
++
++    # Keep the prodvers leading whitespace (Configure magic).
++    # Cannot use $osvers here since that is the kernel version.
++    # sw_vers output                 what we want
++    # "ProductVersion:    10.10.5"   "10.10"
++    # "ProductVersion:    10.11"     "10.11"
++        prodvers=`sw_vers|awk '/^ProductVersion:/{print $2}'|awk -F. '{print $1"."$2}'`
++    case "$prodvers" in
++    [1-9][0-9].*)
++      add_macosx_version_min ccflags $prodvers
++      add_macosx_version_min ldflags $prodvers
++      ;;
++    *)
++      cat <<EOM >&4
++
++*** Unexpected product version $prodvers.
++***
++*** Try running sw_vers and see what its ProductVersion says.
++
++EOM
++      exit 1
++    esac
++
++    darwin_major=$(echo $osvers|awk -F. '{print $1}')
++
++    # macOS 10.12 (darwin 16.0.0) deprecated syscall().
++    if [ "$darwin_major" -ge 16 ]; then
++        d_syscall='undef'
++        # If deploying to pre-10.12, suppress Time::HiRes's detection of the system clock_gettime()
++        case "$MACOSX_DEPLOYMENT_TARGET" in
++          10.[6-9]|10.10|10.11)
++          ccflags="$ccflags -Werror=partial-availability -D_DARWIN_FEATURE_CLOCK_GETTIME=0"
++          ;;
++        *)
++          ;;
++        esac
++    fi
++
++   lddlflags="${ldflags} -bundle -undefined dynamic_lookup"
++   ;;
+ esac
++
+ ldlibpthname='DYLD_LIBRARY_PATH';
+ 
+ # useshrplib=true results in much slower startup times.
+@@ -293,6 +452,11 @@ case "$usemymalloc" in
+ esac
+ # However sbrk() returns -1 (failure) somewhere in lib/unicore/mktables at
+ # around 14M, so we need to use system malloc() as our sbrk()
++#
++# sbrk() in Darwin deprecated since Mavericks (10.9), it still exists
++# in Yosemite (10.10) but that is just an emulation, and fails for
++# allocations beyond 4MB.  One should use e.g. mmap instead (or system
++# malloc, as suggested above, that but is kind of backward).
+ malloc_cflags='ccflags="-DUSE_PERL_SBRK -DPERL_SBRK_VIA_MALLOC $ccflags"'
+ 
+ # Locales aren't feeling well.
+@@ -331,6 +495,11 @@ i_dbm=undef;
+ # NeilW says this should be acceptable on all darwin versions.
+ ranlib='ranlib'
+ 
++# Catch MacPorts gcc/g++ extra libdir
++case "$($cc -v 2>&1)" in
++*"MacPorts gcc"*) loclibpth="$loclibpth /opt/local/lib/libgcc" ;;
 +esac
 +
- case "$libc" in
- '')
- # If you have glibc, then report the version for ./myconfig bug reporting.
-@@ -204,92 +234,6 @@ case "$libc" in
-     ;;
- esac
- 
--# Are we using ELF?  Thanks to Kenneth Albanowski <kjahds@kjahds.com>
--# for this test.
--cat >try.c <<'EOM'
--/* Test for whether ELF binaries are produced */
--#include <fcntl.h>
--#include <stdlib.h>
--#include <unistd.h>
--main() {
--	char buffer[4];
--	int i=open("a.out",O_RDONLY);
--	if(i==-1)
--		exit(1); /* fail */
--	if(read(i,&buffer[0],4)<4)
--		exit(1); /* fail */
--	if(buffer[0] != 127 || buffer[1] != 'E' ||
--           buffer[2] != 'L' || buffer[3] != 'F')
--		exit(1); /* fail */
--	exit(0); /* succeed (yes, it's ELF) */
--}
--EOM
--if ${cc:-gcc} $ccflags $ldflags try.c >/dev/null 2>&1 && $run ./a.out; then
--    cat <<'EOM' >&4
--
--You appear to have ELF support.  I'll try to use it for dynamic loading.
--If dynamic loading doesn't work, read hints/linux.sh for further information.
--EOM
--
--else
--    cat <<'EOM' >&4
--
--You don't have an ELF gcc.  I will use dld if possible.  If you are
--using a version of DLD earlier than 3.2.6, or don't have it at all, you
--should probably upgrade. If you are forced to use 3.2.4, you should
--uncomment a couple of lines in hints/linux.sh and restart Configure so
--that shared libraries will be disallowed.
--
--EOM
--    lddlflags="-r $lddlflags"
--    # These empty values are so that Configure doesn't put in the
--    # Linux ELF values.
--    ccdlflags=' '
--    cccdlflags=' '
--    ccflags="-DOVR_DBL_DIG=14 $ccflags"
--    so='sa'
--    dlext='o'
--    nm_so_opt=' '
--    ## If you are using DLD 3.2.4 which does not support shared libs,
--    ## uncomment the next two lines:
--    #ldflags="-static"
--    #so='none'
--
--	# In addition, on some systems there is a problem with perl and NDBM
--	# which causes AnyDBM and NDBM_File to lock up. This is evidenced
--	# in the tests as AnyDBM just freezing.  Apparently, this only
--	# happens on a.out systems, so we disable NDBM for all a.out linux
--	# systems.  If someone can suggest a more robust test
--	#  that would be appreciated.
--	#
--	# More info:
--	# Date: Wed, 7 Feb 1996 03:21:04 +0900
--	# From: Jeffrey Friedl <jfriedl@nff.ncl.omron.co.jp>
--	#
--	# I tried compiling with DBM support and sure enough things locked up
--	# just as advertised. Checking into it, I found that the lockup was
--	# during the call to dbm_open. Not *in* dbm_open -- but between the call
--	# to and the jump into.
--	#
--	# To make a long story short, making sure that the *.a and *.sa pairs of
--	#   /usr/lib/lib{m,db,gdbm}.{a,sa}
--	# were perfectly in sync took care of it.
--	#
--	# This will generate a harmless Whoa There! message
--	case "$d_dbm_open" in
--	'')	cat <<'EOM' >&4
--
--Disabling ndbm.  This will generate a Whoa There message in Configure.
--Read hints/linux.sh for further information.
--EOM
--		# You can override this with Configure -Dd_dbm_open
--		d_dbm_open=undef
--		;;
--	esac
--fi
--
--rm -f try.c a.out
--
- if ${sh:-/bin/sh} -c exit; then
-   echo ''
-   echo 'You appear to have a working bash.  Good.'
-@@ -497,7 +441,7 @@ then
-        DBLIB="$DBDIR/libdb.so"
-        if [ -f $DBLIB ]
-        then
--         if ${nm:-nm} -u $DBLIB | grep pthread >/dev/null
-+         if ${nm:-nm} -u $DBLIB 2>/dev/null | grep pthread >/dev/null
-          then
-            if ldd $DBLIB | grep pthread >/dev/null
-            then
+ ##
+ # Build process
+ ##
+@@ -339,3 +508,30 @@ ranlib='ranlib'
+ # makefile in the same place.  Since Darwin uses GNU make, this dodges
+ # the problem.
+ firstmakefile=GNUmakefile;
++
++# Parts of the system call setenv(), in particular in an atfork handler.
++# This causes problems when the child tries to clean up environ[], so
++# let libc manage environ[].
++cat >> config.over <<'EOOVER'
++if test "$d_unsetenv" = "$define" -a \
++    `expr "$ccflags" : '.*-DPERL_USE_SAFE_PUTENV'` -eq 0; then
++        ccflags="$ccflags -DPERL_USE_SAFE_PUTENV"
++fi
++EOOVER
++
++# if you use a newer toolchain before OS X 10.9 these functions may be
++# incorrectly detected, so disable them
++# OS X 10.10.x corresponds to kernel 14.x
++case "$osvers" in
++    [1-9].*|1[0-3].*)
++	d_linkat=undef
++	d_openat=undef
++	d_renameat=undef
++	d_unlinkat=undef
++	d_fchmodat=undef
++	;;
++esac
++
++# mkostemp() was autodetected as present but found to not be linkable
++# on 15.6.0.  Unknown what other OS versions are affected.
++d_mkostemp=undef
 diff --git a/pp.c b/pp.c
 index 4ec6887..729239c 100644
 --- a/pp.c
